# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# set the trigger to none so that it only runs manually
trigger: none


pool: Linux

variables:
  SYSTEM_DEBUG: true

jobs:
- job: scan_image
  steps:
    - task: trivy@1
      displayName: 'Container Image Scan'
      inputs:
        trivyImage: 'aquasec/treivy:0.58.2'
        version: 'latest'
        exitCode: '0'
        image: 'nginx'
        severities: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        ignoreUnfixed: true
        sarifOutput: true
        options: '--vuln-type os --timeout 5m'

- job: scan_local_project
  steps:
  - task: trivy@1
    displayName: 'scan dependencies'
    inputs:
      version: 'v0.59.0'
      docker: false
      path: '.'
      severities: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      exitCode: '0'
      ignoreUnfixed: true
      options: '--pkg-types library --timeout 5m'

- job: scan_local_project_again
  steps:
    - task: trivy@1
      inputs:
        docker: false
        version: 'v0.59.0'
        exitCode: '1'
        path: '.'
        cosignOutput: true
        jsonOutput: true
