# set the trigger to none so that it only runs manually
trigger: none


jobs:
- job: scan_image
  steps:
  - task: trivy-dev@1
    inputs:
      image: 'nginx'
      version: 'latest'
      spdxjsonOutput: true

  - task: trivy-dev@2
    inputs:
      type: sbom
      target: $(scan_image.spdxjsonReport)
        
        

