# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# set the trigger to none so that it only runs manually
trigger: none


pool: Linux

variables:
  SYSTEM_DEBUG: true

jobs:
- job: scan_hello
  steps:
  - task: trivy@1
    name: scan_hello_world
    displayName: Scan Hello World
    inputs:
      version: 'latest'
      image: 'hello-world'

- job: scan_nginx
  steps:
  - task: trivy@1
    name: scan_nginx
    displayName: Scan NGINX
    inputs:
      version: 'latest'
      image: 'hello-world'
