# set the trigger to none so that it only runs manually
trigger: none


jobs:
- job: scan_image
  steps:
  - task: trivy-dev@2
    name: scanImage
    inputs:
      version: 'latest'
      type: 'image'
      target: 'nginx'
      reports: 'spdx, spdxjson'
    continueOnError: true

  - task: trivy-dev@2
    inputs:
      type: sbom
      target: $(scanImage.spdxjsonReport)
  
        
        

