# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Scan local project
  steps:
    - task: trivy@1
      inputs:
        path: .

- job: Scan the ubuntu image
  steps:
  - task: trivy@1
    inputs:
      image: nginx
