# set the trigger to none so that it only runs manually
trigger: none


jobs:
- job: scan_image
  steps:
  - task: trivy-dev@2
    inputs:
      version: 'latest'
      options: '--ignorefile .trivyignore.yaml --show-suppressed'
      type: 'filesystem'
      target: '.'
      scanners: 'misconfig, vuln'
      ignoreScanErrors: true

  
        
        

