# set the trigger to none so that it only runs manually
trigger: none


jobs:
- job: scan_local_project
  steps:
  - task: trivy-dev@1
    inputs:
      docker: false
      version: 'latest'
      type: 'repo'
      path: 'https://github.com/owenrumney/trivy-bad'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - task: trivy-dev@1
    inputs:
      docker: false
      path: .
      