# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# set the trigger to none so that it only runs manually
trigger: none


pool: Linux

variables:
  SYSTEM_DEBUG: true

jobs:
- job: scan_hello
  steps:
  - task: trivy@1
    name: scan_hello_world
    displayName: Scan Hello World
    inputs:
      version: 'latest'
      image: 'hello-world'

- job: scan_nginx
  steps:
  - task: trivy@1
    name: scan_nginx
    displayName: Scan NGINX
    inputs:
      version: 'latest'
      image: 'nginx'

- job: use_binary
  steps:
  - task: trivy@1
    displayName: 'Trivy Scan'
    inputs:
      version: 'latest'
      docker: false
      path: '.'
      exitCode: 0
      options: '--scanners vuln,misconfig --db-repository ghcr.io/aquasecurity/trivy-db:2,aquasec/trivy-db:2'
