# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# set the trigger to none so that it only runs manually
trigger: none


pool:
  name: Linux

jobs:
- job: scan_local_project
  steps:
    - task: trivy@1
      inputs:
        version: 'latest'
        debug: true
        image: 'nginx'
    - task: trivy@1
      inputs:
        version: 'latest'
        path: .
