# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# set the trigger to none so that it only runs manually
trigger: none


pool:
  vmImage: ubuntu-22.04

variables:
  SYSTEM_DEBUG: true

jobs:
- job: scan_image
  steps:
    - task: trivy@1
      inputs:
        version: 'v1.59.0'
        debug: true
        image: 'nginx'
        jsonOutput: true

- job: scan_local_project
  steps:
    - task: trivy@1
      inputs:
        docker: false
        version: 'latest'
        exitCode: '0'
        path: '.'
        cosignOutput: true
        sarifOutput: true

- job: scan_local_project_again
  steps:
    - task: trivy@1
      inputs:
        docker: false
        version: 'v0.59.0'
        exitCode: '1'
        path: '.'
        cosignOutput: true
        jsonOutput: true
