# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# set the trigger to none so that it only runs manually
trigger: none

variables:
  SYSTEM_DEBUG: true


jobs:
- job: clone_then_scan
  steps:
  - script: |
        git clone https://github.com/MicrosoftCSUDevAdvUK/real_deal.git
    displayName: 'Clone to temp dir'
    workingDirectory: $(Agent.TempDirectory)
  - task: trivy-dev@1
    inputs:
      docker: false
      path: $(Agent.TempDirectory)/real_deal/assets/css
      exitCode: 0
      scanners: 'vuln,misconfig,secret,license'
  - task: trivy-dev@1
    inputs:
      docker: false
      type: repository
      path: https://github.com/MicrosoftCSUDevAdvUK/real_deal.git
      scanners: 'vuln,misconfig,secret,license'




# - job: use_binary
#   steps:
#   - task: trivy-dev@2
#     inputs:
#         method: 'install'
#         type: 'repo'
#         target: 'https://github.com/owenrumney/trivy-bad'
#         scanners: 'secret,vuln,misconfig'
#         ignoreUnfixed: true
#         ignoreScanErrors: true
#         reports: 'github, junit, sarif'
#     env:
#       GITHUB_TOKEN: $(GITHUB_TOKEN)

