# set the trigger to none so that it only runs manually
trigger: none


jobs:
- job: scan_local_project
  steps:
  - task: trivy-dev@1
    inputs:
      version: 'latest'
      type: repo
      docker: false
      path: 'https://github.com/owenrumney/lazytrivy'