# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# set the trigger to none so that it only runs manually
trigger: none


pool: Linux

variables:
  SYSTEM_DEBUG: true

jobs:
- job: scan_image
  steps:
    - task: trivy@1
      displayName: 'Scan nginx for vulnerabilities and license issues'
      inputs:
        version: 'latest'
        devMode: true
        image: 'nginx'
        scanners: 'vuln,license'
        severities: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        ignoreUnfixed: true
        aquaKey: '$(AQUA_KEY)'
        aquaSecret: '$(AQUA_SECRET)'
        jsonOutput: true
        sarifOutput: true

- job: scan_local_project
  steps:
  - task: trivy@1
    displayName: 'Scan project for everything'
    inputs:
      docker: false
      version: 'v0.59.0'
      type: 'filesystem'
      path: '.'
      scanners: 'vuln,misconfig,secret,license'
      severities: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      ignoreUnfixed: true
      options: '--pkg-types library --timeout 5m'

