# set the trigger to none so that it only runs manually
trigger: none

pool: Linux

jobs:
- job:
  steps:
    - task: trivy@1
      name: hello_world
      displayName: Check Hello World
      inputs:
        image: hello-world

- job:
  steps:
    - task: trivy@1
      name: nginx
      displayName: Check nginx
      inputs:
        image: nginx
        
# - job: scan_image
#   steps:
#     - task: trivy@1
#       name: trivy_nginx
#       displayName: 'Scan nginx for vulnerabilities and license issues'
#       inputs:
#         version: 'latest'
#         image: 'nginx'
#         scanners: 'vuln,license'
#         severities: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
#         ignoreUnfixed: true
#         jsonOutput: true
#         sarifOutput: true
#     - task: CmdLine@2
#       name: prove_output_var
#       condition: always()
#       inputs:
#         script: 'echo $(trivy_nginx.jsonReport)'

- job: scan_local_project
  steps:
    - task: trivy@1
      displayName: 'Scan project for everything'
      inputs:
        version: 'v0.59.0'
        type: 'filesystem'
        path: '.'
        scanners: 'vuln,misconfig,secret,license'
        severities: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        ignoreUnfixed: true
        options: '--ignorefile .trivyignore  --db-repository ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2 --java-db-repository ghcr.io/aquasecurity/trivy-java-db:1,public.ecr.aws/aquasecurity/trivy-java-db:1'
        # devMode: true
        # aquaKey: '$(AQUA_KEY)'
        # aquaSecret: '$(AQUA_SECRET)'

