# set the trigger to none so that it only runs manually
trigger: none


jobs:
- job: scan_image
  steps:
  - task: trivy-dev@2
    inputs:
      version: 'latest'
      type: 'filesystem'
      target: '.'
      scanners: 'vuln,misconfig'
      showSuppressed: true
      failOnSeverityThreshold: 'CRITICAL'
      trivyUrl: https://get.trivy.dev/trivy?os=linux&arch=amd64
      reports: table

